### ISSUE TITLE
Skype.class.php

### ISSUE THREAD

**Issue by tcolonel** [alissonpelizaro/SkypePHP#8]
Hello @alissonpelizaro.

There are questions about some of the methods.

**loginRequest**

What is the **client_id** parameter? Why is it being set statically? How to get it - for yourself?

Thanks.

**Comment by alissonpelizaro** [comment]
Hi @tcolonel , thanks for your interesting...

Sorry my delay, i've stopped working on this project a long time ago. But i remember that this `client_id` is a randon ID provided by UI Skype application on login form, and its not mandatory to perform a login. That's why this is statically declareted.
